### ISSUE TITLE
提示json错误

### ISSUE THREAD

**Issue by goulin** [wu-dada/baidupankey#11]
命令: bdp -u https://pan.baidu.com/s/1o1QR_hzWM0IvfLuc4OgefQ

----提示如下:----
undefined:1
神秘人士～
^

SyntaxError: Unexpected token 神 in JSON at position 0
    at JSON.parse (<anonymous>)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/baidupankey/lib/baidupan.js:27:34)
    at IncomingMessage.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1094:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)

**Comment by lriuui0x0** [comment]
同样的结果，API不好用了。
